# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true

# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true

# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL: /api/

# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/

# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql

spring:
#  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_dataway
    username: root
    password: root
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60
      # 设置用户名和密码
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1
  # springboot 2.6 发布了一个重要的更新，是将处理映射匹配的默认策略由AntPathMatcher改为PathPatternParser，
  # 这个改动，影响了许多使用自定义Filter的项目，同样影响了dataway。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 解决中文乱码
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

